version: '3'
services:
  pos-sim-core:
    network_mode: "host"
    image: 'pos-sim-core:latest'
    container_name: 'pos-sim-core'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./data:/home/production/data
    # ports:
    #   - '27020-27022:27017-27019'
